name: electricity_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  google_mobile_ads: ^6.0.0
  shimmer: ^3.0.0
  connectivity_plus: ^6.1.4
  url_launcher: ^6.3.1
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  http:
  country_flags: ^3.1.0
  flutter_screenutil:
  sqflite:
  just_audio:
  flutter_tts: ^4.2.2
  permission_handler:
  path:
  speech_to_text: ^7.0.0
  path_provider: ^2.1.5
  translator: ^1.0.3+1
  intl: ^0.20.1
  share_plus:
  google_generative_ai: ^0.4.7
  in_app_purchase: ^3.2.0
  app_tracking_transparency: ^2.0.6+1
  swipeable_button_view: ^0.0.2
  onesignal_flutter: ^5.0.0
  carousel_slider: ^5.1.1
  lottie: ^3.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  source_gen: ^1.2.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.7.0

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/db/wordsnew_db.db
    - assets/db/db_prahse.db
    - assets/db/dictionary.db
    - assets/trial/
    - assets/won.json

#scripts:
#  gen: flutter pub run build_runner build --delete-conflicting-outputs
